AWSTemplateFormatVersion: "2010-09-09"
Description: DiscordClone backend service (App Runner) with environment parameters and GitHub connection

Parameters:
  Environment:
    Type: String
    AllowedValues: [dev, prod]
    Description: Deployment environment (dev or prod)

  RepositoryUrl:
    Type: String
    Description: GitHub repository URL (e.g., https://github.com/wizzerrd/DiscordCloneNew)

  Branch:
    Type: String
    Default: main
    Description: Branch to deploy from (e.g., main, auth)

  GitHubConnectionArn:
    Type: String
    Description: ARN of the AWS App Runner GitHub connection

  CognitoRegion:
    Type: String
    Description: Cognito region for JWT verification

  CognitoPoolId:
    Type: String
    Description: Cognito User Pool ID

  CognitoClientId:
    Type: String
    Description: Cognito App Client ID

  AllowedOrigins:
    Type: String
    Description: Comma-separated list of allowed origins for CORS (e.g., https://frontend.cloudfront.net)

Resources:
  AppRunnerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "discordclone-apprunner-role-${Environment}"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: apprunner.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess

  BackendService:
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: !Sub "discordclone-backend-${Environment}"
      SourceConfiguration:
        AuthenticationConfiguration:
          ConnectionArn: !Ref GitHubConnectionArn
        AutoDeploymentsEnabled: true
        CodeRepository:
          RepositoryUrl: !Ref RepositoryUrl
          SourceCodeVersion:
            Type: BRANCH
            Value: !Ref Branch
          CodeConfiguration:
            ConfigurationSource: API
            CodeConfigurationValues:
              Runtime: NODEJS_18
              BuildCommand: "npm install"
              StartCommand: "npm start"
              Port: "8000"
              RuntimeEnvironmentVariables:
                - Name: NODE_ENV
                  Value: !Ref Environment
                - Name: PORT
                  Value: "8000"
                - Name: COGNITO_REGION
                  Value: !Ref CognitoRegion
                - Name: COGNITO_POOL_ID
                  Value: !Ref CognitoPoolId
                - Name: COGNITO_CLIENT_ID
                  Value: !Ref CognitoClientId
                - Name: ALLOWED_ORIGINS
                  Value: !Ref AllowedOrigins
      InstanceConfiguration:
        Cpu: "1024"
        Memory: "2048"
      HealthCheckConfiguration:
        Protocol: HTTP
        Path: "/health"
        Interval: 10
        Timeout: 5
        HealthyThreshold: 3
        UnhealthyThreshold: 3
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: DiscordClone

Outputs:
  BackendServiceUrl:
    Description: Public URL of the App Runner backend service
    Value: !GetAtt BackendService.ServiceUrl

  BackendServiceArn:
    Description: ARN of the App Runner service
    Value: !Ref BackendService

  AppRunnerDashboard:
    Description: Console URL for the App Runner service dashboard
    Value: !Sub "https://${AWS::Region}.console.aws.amazon.com/apprunner/home?region=${AWS::Region}#/services/${BackendService}"
